[platformio]
src_dir = main
default_envs = m5stack-cores3

[env:m5stack-cores3]
platform = espressif32@7.0.1
board = m5stack-cores3
framework = espidf
build_flags = -std=gnu++20
extra_scripts = pre:scripts/enable_idf_component_manager.py
monitor_speed = 115200
board_build.cmake_extra_args = -DSDKCONFIG_DEFAULTS="sdkconfig.defaults"
board_build.partitions = partitions.csv

[env:m5stack-cores3-debug]
extends = env:m5stack-cores3
build_type = debug
debug_tool = esp-builtin
upload_protocol = esp-builtin
debug_init_break = tbreak app_main
